### ISSUE TITLE
Default institution environment variable

### ISSUE THREAD

**Issue by duncanmmacleod** [fermitools/cigetcert#60]
Is it reasonable to have a default institution configured, probably best through an environment variable? Something like:

```
export CIGETCERT_INSTITUTION="LIGO Scientific Collaboration"
cigetcert -u duncan.macleod
```

**Comment by DrDaveD** [comment]
Yes I expect most people would want to set a default institution.  There's already an environment variable CIGETCERTOPTS, and the man page shows an example of using it to set a default institution.

**Comment by DrDaveD** [comment]
Does that solve the issue, can we close this one?
