### ISSUE TITLE
PyPI package for cigetcert

### ISSUE THREAD

**Issue by duncanmmacleod** [fermitools/cigetcert#63]
I would like to bundle and distribute `cigetcert` using pypi.python.org, to enable `pip install cigetcert`. Are there any objections to me going ahead and just doing this?

In practice this just means

```
python setup.py sdist
python -m twine upload dist/cigetcert-*.tar.gz
```

I would then like to 'subscribe' in some way to updates about new releases, so that I can keep the pypi package up-to-date.

**Comment by DrDaveD** [comment]
I have no objections.  You can Watch the repository and you should get all messages about issues, PRs, and releases.

**Comment by duncanmmacleod** [comment]
Ok great, I have signed up to watch releases, so should be able to keep this up-to-date.

**Comment by duncanmmacleod** [comment]
https://pypi.org/project/cigetcert/
