### ISSUE TITLE
Conda (conda-forge) package for cigetcert

### ISSUE THREAD

**Issue by duncanmmacleod** [fermitools/cigetcert#64]
I would like to bundle and distribute `cigetcert` using `conda-build` on the [conda-forge](https://conda-forge.org) channel, to enable `conda install -c conda-forge cigetcert`. Are there any objections to me going ahead and just doing this?

In practice this means writing a 'recipe' to build the conda package (very similar to an RPM spec file) and then maintaining it independently.

**Comment by DrDaveD** [comment]
I don't have any objections.  It might make sense to keep the recipe in the package too, submit it as a PR.

**Comment by duncanmmacleod** [comment]
Typically recipes are held separately by the conda-forge organisation. I will post a link once the recipe has been created.

**Comment by duncanmmacleod** [comment]
This package has been created, the package info page is here:

https://anaconda.org/conda-forge/cigetcert

The recipe is held in a feedstock repo here:

https://github.com/conda-forge/cigetcert-feedstock/

I don't recommend duplicating the recipe files in this repo, keeping them synced will inevitably get messy.

The conda-forge build bots will automatically detect new releases on pypi.org and post a PR to update the conda-forge recipe, so the maintenance burden for me is almost zero - I just need to check for each release that the dependencies are up-to-date.

One thing that came up in preparing the recipe was windows support - which is lacking due to the dependency on `pykerberos` - I will have a go at patching `cigetcert` to try and use `winkerberos` on Windows, in an attempt to support that platform.
